### ISSUE TITLE
Memory leak on pipeline creation on Parrot OS 6.0

### ISSUE THREAD

**Issue by Verficif** [owenwijaya22/KernelxPipeline#1]
I observed that both creation and writing operations of the pipeline make my laptop has a spike in memory usage? Any thoughts?

**Comment by owenwijaya22** [comment]
hey, do you have a custom memory profiler that you can use to give me the logs?

**Comment by Verficif** [comment]
shoot i don't have at the moment, never used those kind of tools b4 XD

**Comment by owenwijaya22** [comment]
understandable HAHAH, no worries. for parrot OS I think you should make a custom free operation in the C that should be very simple to do. I believe that can help to resolve your issue. Feel free to ask me how! I will elaborate for u mwa

**Comment by Verficif** [comment]
OH, actually makes sense. I recall the new parrot os isn't stable yet. thanks much bro
